// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erzycacznhlzjdcxrvtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyenljYWN6bmhsempkY3hydnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQzNzksImV4cCI6MjA3MzU5MDM3OX0.-lOYgXyVEVwYDe2aNw7OiT5rqN0YSPjPxfmMAfvX1vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});